name: Test
on:
  workflow_dispatch:
    inputs:
      path:
        description: Enter the path of the resource pack to test.
          (Programmer-Art-Plus, SummerFields, golden-days/golden-days-base)
        required: true
jobs:
  test-master:

    if: github.event.inputs.path == 'Programmer-Art-Plus' ||
      github.event.inputs.path == 'SummerFields' ||
      github.event.inputs.path == 'golden-days/golden-days-base'

    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set Git author
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Apply patches
        run: ./scripts/apply-patch.sh
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@master
        with:
          path: ${{ github.event.inputs.path }}
          allow_optifine_mod: true
          maximum_image_width_and_height: 65535
          artifact_name: ${{ github.event.inputs.path }} ${{ github.job }}

  test-v2:

    if: github.event.inputs.path == 'Programmer-Art-Plus' ||
      github.event.inputs.path == 'SummerFields' ||
      github.event.inputs.path == 'golden-days/golden-days-base'

    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set Git author
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Apply patches
        run: ./scripts/apply-patch.sh
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v2
        with:
          path: ${{ github.event.inputs.path }}
          allow_optifine_mod: true
          maximum_image_width_and_height: 65535
          artifact_name: ${{ github.event.inputs.path }} ${{ github.job }}

  test-v3:

    if: github.event.inputs.path == 'Programmer-Art-Plus' ||
      github.event.inputs.path == 'SummerFields' ||
      github.event.inputs.path == 'golden-days/golden-days-base'

    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set Git author
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Apply patches
        run: ./scripts/apply-patch.sh
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          path: ${{ github.event.inputs.path }}
          allow_optifine_mod: true
          maximum_image_width_and_height: 65535
          artifact_name: ${{ github.event.inputs.path }} ${{ github.job }}
